// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3543.Team3543Robot.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3543.Team3543Robot.Robot;
import org.usfirst.frc3543.Team3543Robot.subsystems.VisionSubsystem.GearDrop;

/**
 *
 */
public class ApproachGearDropCommand extends Command {
	public static final long DEFAULT_MAX_SEARCH_TIME = 15000;	// 15 seconds

	boolean giveUp = false;
	long searchStartTime = System.currentTimeMillis();
	long maxSearchTime = DEFAULT_MAX_SEARCH_TIME;
	
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public ApproachGearDropCommand() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.visionSubsystem);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveLine);

    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	// reset the vision system - will nullify the detection
    	giveUp = false;
    	searchStartTime = System.currentTimeMillis();
    	Robot.visionSubsystem.reset();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	// check the vision system to see if we "see" the gear drop
    	
    	if (Robot.visionSubsystem.isGearDropDetected()) {
        	// if so, approach it
    		approachGearDrop(Robot.visionSubsystem.getGearDrop());
    	}
    	else if (System.currentTimeMillis() - searchStartTime > maxSearchTime) {
        	// if our search fails, quit
    		abandonSearch();
    	}
    	else {
        	// otherwise we search for it    		
    		searchForGearDrop();
    	}
    }
    
    private void searchForGearDrop() {
		// TODO Auto-generated method stub
		
	}

	private void abandonSearch() {
		giveUp = true;
		end();		
	}

	private void approachGearDrop(GearDrop gearDrop) {
		// TODO - figure this out
		// if we are rotated away from it, rotate towards it
		// if we are offset, turn towards it, drive towards it		
	}

	public void setMaxSearchTime(long time) {
    	maxSearchTime = time;
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return giveUp;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.driveLine.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	abandonSearch();
    }
}
